// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KronoWeaveAPI.Models
{
    public partial class License
    {
        public int Id { get; set; }
        public string License1 { get; set; }
        public int? UserId { get; set; }
    }
}