// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KronoWeaveAPI.Models
{
    public partial class Workflows
    {
        public int Id { get; set; }
        public string WorkflowName { get; set; }
        public int? Version { get; set; }
        public string Status { get; set; }
        public string LockedBy { get; set; }
        public bool? Locked { get; set; }
    }
}